"""Verify an observation -> action vector against an exported ONNX actor."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import onnxruntime as ort


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vector", type=Path, help="JSON vector generated by export_policy.py --vector-output.")
    parser.add_argument("--onnx", type=Path, default=None, help="Override ONNX path. Defaults to vector['onnx_model'].")
    parser.add_argument("--atol", type=float, default=1e-5, help="Maximum allowed absolute action error.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    with args.vector.open("r", encoding="utf-8") as f:
        vector = json.load(f)

    onnx_path = args.onnx or Path(vector["onnx_model"])
    observation = np.asarray(vector["observation"], dtype=np.float32).reshape(1, -1)
    expected_action = np.asarray(vector["action"], dtype=np.float32).reshape(1, -1)

    session = ort.InferenceSession(str(onnx_path), providers=["CPUExecutionProvider"])
    action = session.run(["action"], {"observation": observation})[0]
    abs_diff = np.abs(action - expected_action)
    report = {
        "vector": str(args.vector),
        "onnx_model": str(onnx_path),
        "observation_dim": int(observation.shape[1]),
        "action_dim": int(action.shape[1]),
        "max_abs_diff": float(abs_diff.max()),
        "mean_abs_diff": float(abs_diff.mean()),
        "atol": args.atol,
        "passed": bool(abs_diff.max() <= args.atol),
    }
    print(json.dumps(report, indent=2))
    if not report["passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
