#!/usr/bin/env python3
"""Dry-run or send first-day Bittle bring-up protocol probes."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR / "tools") not in sys.path:
    sys.path.insert(0, str(ROOT_DIR / "tools"))

from rl_serial_protocol_v0 import (
    decode_frame,
    encode_get_state_request,
    encode_set_targets_request,
    parse_target_arg,
    send_serial_request,
    serial_frame_to_json,
)


def load_vectors(path: Path) -> dict[str, object]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def print_sequence(vectors: dict[str, object]) -> None:
    sequence = vectors["set_target_sequence"]
    summary = {
        "version": vectors["version"],
        "source_config": vectors["source_config"],
        "joint_order": vectors["joint_order"],
        "get_state_request": vectors["get_state_request"],
        "set_target_count": len(sequence),
        "set_target_tests": [
            {
                "index": index,
                "sequence_id": item["sequence_id"],
                "test": item.get("test", "neutral"),
                "joint_name": item.get("joint_name"),
                "phase": item.get("phase"),
                "target_joint_rad": item["target_joint_rad"],
            }
            for index, item in enumerate(sequence)
        ],
    }
    print(json.dumps(summary, indent=2))


def selected_targets(vectors: dict[str, object], index: int) -> tuple[int, list[float]]:
    sequence = vectors["set_target_sequence"]
    if index < 0 or index >= len(sequence):
        raise SystemExit(f"--index must be in [0, {len(sequence) - 1}]")
    item = sequence[index]
    return int(item["sequence_id"]), [float(value) for value in item["target_joint_rad"]]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--vectors",
        type=Path,
        default=ROOT_DIR / "protocol/test_vectors/bittle_bringup_v0.json",
        help="Bring-up vector JSON generated by tools/generate_bittle_bringup_vectors.py.",
    )
    parser.add_argument("--list", action="store_true", help="List generated bring-up tests.")
    parser.add_argument("--port", default=None, help="Serial port, e.g. /dev/ttyUSB0.")
    parser.add_argument("--baud", type=int, default=115200, help="Serial baud rate.")
    parser.add_argument("--timeout", type=float, default=1.0, help="Serial timeout in seconds.")
    parser.add_argument("--rl-token", default="Y", help="OpenCat token prepended before RL frames.")
    parser.add_argument("--get-state", action="store_true", help="Send or print one RL_GET_STATE request.")
    parser.add_argument("--index", type=int, default=None, help="Index from --list to use for RL_SET_TARGETS.")
    parser.add_argument(
        "--targets",
        default=None,
        help="Manual 8 comma-separated target angles in radians. Use only after mapping is verified.",
    )
    parser.add_argument("--allow-motion", action="store_true", help="Required before sending RL_SET_TARGETS to --port.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    vectors = load_vectors(args.vectors)

    if args.list:
        print_sequence(vectors)
        return

    requests: list[tuple[str, bytes]] = []
    if args.get_state:
        requests.append(("get_state", encode_get_state_request(1)))

    if args.index is not None and args.targets is not None:
        raise SystemExit("Use either --index or --targets, not both.")
    if args.index is not None:
        sequence_id, targets = selected_targets(vectors, args.index)
        requests.append((f"set_targets_index_{args.index}", encode_set_targets_request(sequence_id, targets)))
    if args.targets is not None:
        requests.append(("set_targets_manual", encode_set_targets_request(2, parse_target_arg(args.targets))))

    if not requests:
        print_sequence(vectors)
        return

    motion_requests = [name for name, frame in requests if decode_frame(frame).message_type == 0x02]
    if args.port and motion_requests and not args.allow_motion:
        raise SystemExit("--allow-motion is required before sending RL_SET_TARGETS to hardware.")

    if not args.port:
        output = [
            {
                "request": name,
                "wire_hex_with_token": (args.rl_token.encode("latin1") + frame).hex(),
            }
            for name, frame in requests
        ]
        print(json.dumps(output, indent=2))
        return

    try:
        import serial
    except ImportError as exc:
        raise SystemExit("pyserial is required for --port. Install it with: python3 -m pip install pyserial") from exc

    responses = []
    with serial.Serial(args.port, args.baud, timeout=args.timeout) as port:
        for name, frame in requests:
            response = send_serial_request(port, frame, args.rl_token.encode("latin1"))
            responses.append({"request": name, "response": serial_frame_to_json(response)})
    print(json.dumps(responses, indent=2))


if __name__ == "__main__":
    main()
